### ISSUE TITLE
[robot_state_publisher-3] process has died

### ISSUE THREAD

**Issue by gitasma** [Polarbeargo/RoboND-Where-Am-I#1]
When I type this command $ roslaunch udacity_bot udacity_world.launch ,
Everything works fine, but then suddenly the robot_state_publisher process dies!
Also, I can't find the robot_state_publisher log file i don't know why..
This is my first time working with ros, and my first time to work with the virtual machine. I did a lot of research and tried many things, but still I couldn't make it work.
Can you help me please?  
@Polarbeargo  

![Screenshot 2021-01-30 214434](https://user-images.githubusercontent.com/66415170/106368159-4587e700-6350-11eb-91df-e03559b9ac6e.png)

**Comment by polarbeargo** [comment]
@asmahigh Follow this post to fix your project [robot_state_publisher has died, joint_state_publisher has died](https://answers.ros.org/question/323094/robot_state_publisher-has-died-joint_state_publisher-has-died/) and post your future question in the Udacity Knowledge hubs where you can get more help from there.
